# Generated by Django 4.1.5 on 2023-01-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='상품명')),
                ('content', models.TextField(verbose_name='상품내용')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('location', models.CharField(max_length=256, verbose_name='위치')),
            ],
            options={
                'db_table': 'shinhan_project',
            },
        ),
    ]
