# Generated by Django 4.1.5 on 2023-01-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='비밀번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='user_id',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='아이디'),
            preserve_default=False,
        ),
    ]
